actions:
  discrete_actions: 5
game_over_pixel:
  BLUE: 6
  GREEN: 6
  RED: 6
  left: 400
  top: 400
game_region:
  height: 677
  left: 78
  top: 222
  width: 768
input_shape:
  frame_stack: 4
  height: 30
  width: 34
preprocessing:
  fps: 10
  grayscale: true
score_capture:
  height: 270
  left: 70
  top: 25
  width: 60
