actions:
  # "discrete" or "continuous"
  action_space: discrete
  discrete_actions: 4
  continuous_low: [-1.0, -1.0, 0.0]
  continuous_high: [1.0, 1.0, 1.0]
game_over_pixel:
  BLUE: 6
  GREEN: 6
  RED: 6
  left: 600
  top: 1000
game_region:
  height: 1440
  left: 0
  top: 0
  width: 2560
input_shape:
  frame_stack: 1
  height: 81
  width: 144
preprocessing:
  fps: 20
  grayscale: true
score_capture:
  height: 40
  left: 200
  top: 170
  width: 100